inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Security/Open:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false
